'use strict';
var bcrypt = require('bcryptjs');
const User = require('./User');


// Sorry for bad namings and bad codes ;)


exports.findAll = function (req, res) {
  
    User.findAll(function (err, user) {
        if (err)
        res.send(err);
        res.send(user);
    });
};

exports.create = function (req, res) {
     
     // hashing password
     req.body['password'] = bcrypt.hashSync(req.body['password'], 10);

    
    // Constructing
    const new_user = new User(req.body);
    if (req.body.constructor === Object && Object.keys(req.body).length === 0) {
        res.status(400).send({ error: true, message: 'Please provide all required field' });
    }

       
    
    // Checking presence of all fields
    if (req.body['email'] && req.body['password'] && req.body['plan'] && req.body['isActive']) {
        
        //Checking if same email exists  
        User.findByEmail(req.body['email'], function (error, result) {
            
            if (result.length != 0) {
                res.status(400).json({ message: "Email already exists!" });
            }
            else {
                User.create(new_user, function (err, user) {
                    if (err)
                        res.send(err);
                    res.json({ message: "User added successfully!", user_id: user });
                });
            }

        });
    }
    else {
        res.status(404).send({ error: true, message: 'Please provide all the required fields' });
    }

};

exports.findById = function (req, res) {

    // Caling User Model Data Access Objects
    // Here req.userId is generated by verifyToken 
    User.findById(req.userId, function (err, user) {
        if (err)
            res.send(err);

        if (user.length != 0) {
            res.json(user);
        }else {
            res.json({ message: "User Does Not Exists" });
        }

    });

};

exports.update = function (req, res) {

    if (req.body.constructor === Object && Object.keys(req.body).length === 0) {
        res.status(400).send({ error: true, message: 'Please provide all required field' });
    }
    else {
        
        if (req.body['plan'] && req.body['isActive']) {
            User.update(req.userId, new User(req.body), function (err, user) {
                if (err)
                    res.send(err);
                if (user) {
                    res.json({ message: 'User successfully updated', data: user });
                }
                else {
                    res.json({ message: "User Does Not Exists" })
                }
            });
        }
        else {
            res.json({ message: "Check fields once, Email cannot be changed!!" });
        }

    }

};

exports.delete = function (req, res) {
    User.delete(req.userId, function (err, user) {
        if (err)
            res.send(err);
        if (user) {
            res.json({ message: 'User successfully deleted' });
        }
        else {
            res.json({ message: "Does Not Exist" })
        }
    });
};